let charityChildPath = "charitys"

let charityNameChildPath = "charityname"
let charityAboutChildPath = "about"
let charityCategoryChildPath = "category"
let charityImpactPerDollarChildPath = "impactperdollar"
let charityImpactTypeChildPath = "impacttype"
let charityLongInformationChildPath = "longinformation"
let charitySourceLinkChildPath = "sourcelink"
let charityWebsiteChildPath = "website"
let charityLogoChildPath = "logo"
