let charityChildPath = "charitys"
let charityNameChildPath = "charityname"
let charityAboutChildPath = "about"
let charityImpactPerDollarChildPath = "impactperdollar"
let charityImpactTypeChildPath = "impacttype"
let charityLongInformationChildPath = "longinformation"
let charitySourceLinkChildPath = "sourcelink"
let charityWebsiteChildPath = "website"
